// Code generated by go-swagger; DO NOT EDIT.

package player

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"DatsMagic/models"
)

// NewPostPlayMagcarpPlayerMoveParams creates a new PostPlayMagcarpPlayerMoveParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostPlayMagcarpPlayerMoveParams() *PostPlayMagcarpPlayerMoveParams {
	return &PostPlayMagcarpPlayerMoveParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostPlayMagcarpPlayerMoveParamsWithTimeout creates a new PostPlayMagcarpPlayerMoveParams object
// with the ability to set a timeout on a request.
func NewPostPlayMagcarpPlayerMoveParamsWithTimeout(timeout time.Duration) *PostPlayMagcarpPlayerMoveParams {
	return &PostPlayMagcarpPlayerMoveParams{
		timeout: timeout,
	}
}

// NewPostPlayMagcarpPlayerMoveParamsWithContext creates a new PostPlayMagcarpPlayerMoveParams object
// with the ability to set a context for a request.
func NewPostPlayMagcarpPlayerMoveParamsWithContext(ctx context.Context) *PostPlayMagcarpPlayerMoveParams {
	return &PostPlayMagcarpPlayerMoveParams{
		Context: ctx,
	}
}

// NewPostPlayMagcarpPlayerMoveParamsWithHTTPClient creates a new PostPlayMagcarpPlayerMoveParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostPlayMagcarpPlayerMoveParamsWithHTTPClient(client *http.Client) *PostPlayMagcarpPlayerMoveParams {
	return &PostPlayMagcarpPlayerMoveParams{
		HTTPClient: client,
	}
}

/*
PostPlayMagcarpPlayerMoveParams contains all the parameters to send to the API endpoint

	for the post play magcarp player move operation.

	Typically these are written to a http.Request.
*/
type PostPlayMagcarpPlayerMoveParams struct {

	/* Request.

	   list of transports with desired acceleration
	*/
	Request *models.CommandPlayer

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post play magcarp player move params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostPlayMagcarpPlayerMoveParams) WithDefaults() *PostPlayMagcarpPlayerMoveParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post play magcarp player move params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostPlayMagcarpPlayerMoveParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post play magcarp player move params
func (o *PostPlayMagcarpPlayerMoveParams) WithTimeout(timeout time.Duration) *PostPlayMagcarpPlayerMoveParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post play magcarp player move params
func (o *PostPlayMagcarpPlayerMoveParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post play magcarp player move params
func (o *PostPlayMagcarpPlayerMoveParams) WithContext(ctx context.Context) *PostPlayMagcarpPlayerMoveParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post play magcarp player move params
func (o *PostPlayMagcarpPlayerMoveParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post play magcarp player move params
func (o *PostPlayMagcarpPlayerMoveParams) WithHTTPClient(client *http.Client) *PostPlayMagcarpPlayerMoveParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post play magcarp player move params
func (o *PostPlayMagcarpPlayerMoveParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post play magcarp player move params
func (o *PostPlayMagcarpPlayerMoveParams) WithRequest(request *models.CommandPlayer) *PostPlayMagcarpPlayerMoveParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post play magcarp player move params
func (o *PostPlayMagcarpPlayerMoveParams) SetRequest(request *models.CommandPlayer) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostPlayMagcarpPlayerMoveParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
