// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DtoRoundList dto round list
//
// swagger:model dto.RoundList
type DtoRoundList struct {

	// game name
	// Example: defense
	GameName string `json:"gameName,omitempty"`

	// now
	// Example: 2021-01-01T00:00:00Z
	Now string `json:"now,omitempty"`

	// rounds
	Rounds []*DtoRound `json:"rounds"`
}

// Validate validates this dto round list
func (m *DtoRoundList) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRounds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DtoRoundList) validateRounds(formats strfmt.Registry) error {
	if swag.IsZero(m.Rounds) { // not required
		return nil
	}

	for i := 0; i < len(m.Rounds); i++ {
		if swag.IsZero(m.Rounds[i]) { // not required
			continue
		}

		if m.Rounds[i] != nil {
			if err := m.Rounds[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("rounds" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("rounds" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this dto round list based on the context it is used
func (m *DtoRoundList) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateRounds(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DtoRoundList) contextValidateRounds(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Rounds); i++ {

		if m.Rounds[i] != nil {

			if swag.IsZero(m.Rounds[i]) { // not required
				return nil
			}

			if err := m.Rounds[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("rounds" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("rounds" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *DtoRoundList) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoRoundList) UnmarshalBinary(b []byte) error {
	var res DtoRoundList
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
