// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DtoRound dto round
//
// swagger:model dto.Round
type DtoRound struct {

	// duration
	// Example: 60
	Duration int64 `json:"duration,omitempty"`

	// end at
	// Example: 2021-01-01T00:00:00Z
	EndAt string `json:"endAt,omitempty"`

	// name
	// Example: Round 1
	Name string `json:"name,omitempty"`

	// repeat
	// Example: 1
	Repeat int64 `json:"repeat,omitempty"`

	// start at
	// Example: 2021-01-01T00:00:00Z
	StartAt string `json:"startAt,omitempty"`

	// status
	// Example: active
	Status string `json:"status,omitempty"`
}

// Validate validates this dto round
func (m *DtoRound) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto round based on context it is used
func (m *DtoRound) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoRound) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoRound) UnmarshalBinary(b []byte) error {
	var res DtoRound
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
