// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PlaneVector plane vector
//
// swagger:model plane.Vector
type PlaneVector struct {

	// x
	// Example: 1.2
	X float64 `json:"x,omitempty"`

	// y
	// Example: 1.2
	Y float64 `json:"y,omitempty"`
}

// Validate validates this plane vector
func (m *PlaneVector) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this plane vector based on context it is used
func (m *PlaneVector) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PlaneVector) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PlaneVector) UnmarshalBinary(b []byte) error {
	var res PlaneVector
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
