// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PuberrPubErr puberr pub err
//
// swagger:model puberr.PubErr
type PuberrPubErr struct {

	// err code
	// Example: 22
	ErrCode int32 `json:"errCode,omitempty"`

	// error
	// Example: description of the error
	Error string `json:"error,omitempty"`
}

// Validate validates this puberr pub err
func (m *PuberrPubErr) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this puberr pub err based on context it is used
func (m *PuberrPubErr) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PuberrPubErr) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PuberrPubErr) UnmarshalBinary(b []byte) error {
	var res PuberrPubErr
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
