// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SwaggerErrForbidden swagger err forbidden
//
// swagger:model swagger.ErrForbidden
type SwaggerErrForbidden struct {

	// err code
	// Example: 26
	ErrCode int32 `json:"errCode,omitempty"`

	// error
	// Example: forbidden or user is banned
	Error string `json:"error,omitempty"`
}

// Validate validates this swagger err forbidden
func (m *SwaggerErrForbidden) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this swagger err forbidden based on context it is used
func (m *SwaggerErrForbidden) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SwaggerErrForbidden) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SwaggerErrForbidden) UnmarshalBinary(b []byte) error {
	var res SwaggerErrForbidden
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
