// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SwaggerErrTooManyUserRequests swagger err too many user requests
//
// swagger:model swagger.ErrTooManyUserRequests
type SwaggerErrTooManyUserRequests struct {

	// err code
	// Example: 24
	ErrCode int32 `json:"errCode,omitempty"`

	// error
	// Example: too many requests from this user
	Error string `json:"error,omitempty"`
}

// Validate validates this swagger err too many user requests
func (m *SwaggerErrTooManyUserRequests) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this swagger err too many user requests based on context it is used
func (m *SwaggerErrTooManyUserRequests) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SwaggerErrTooManyUserRequests) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SwaggerErrTooManyUserRequests) UnmarshalBinary(b []byte) error {
	var res SwaggerErrTooManyUserRequests
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
