// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ViewBounty view bounty
//
// swagger:model view.Bounty
type ViewBounty struct {

	// points
	// Example: 100
	Points int64 `json:"points,omitempty"`

	// radius
	// Example: 10
	Radius int64 `json:"radius,omitempty"`

	// x
	// Example: 1
	// Required: true
	X *int64 `json:"x"`

	// y
	// Example: 1
	// Required: true
	Y *int64 `json:"y"`
}

// Validate validates this view bounty
func (m *ViewBounty) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateX(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateY(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ViewBounty) validateX(formats strfmt.Registry) error {

	if err := validate.Required("x", "body", m.X); err != nil {
		return err
	}

	return nil
}

func (m *ViewBounty) validateY(formats strfmt.Registry) error {

	if err := validate.Required("y", "body", m.Y); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this view bounty based on context it is used
func (m *ViewBounty) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ViewBounty) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ViewBounty) UnmarshalBinary(b []byte) error {
	var res ViewBounty
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
