// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ViewTransport view transport
//
// swagger:model view.Transport
type ViewTransport struct {

	// anomaly acceleration
	AnomalyAcceleration *PlaneVector `json:"anomalyAcceleration,omitempty"`

	// attack cooldown ms
	// Example: 0
	AttackCooldownMs int64 `json:"attackCooldownMs,omitempty"`

	// death count
	// Example: 0
	DeathCount int64 `json:"deathCount,omitempty"`

	// health
	// Example: 100
	Health int64 `json:"health,omitempty"`

	// id
	// Example: 00000000-0000-0000-0000-000000000000
	ID string `json:"id,omitempty"`

	// self acceleration
	SelfAcceleration *PlaneVector `json:"selfAcceleration,omitempty"`

	// shield cooldown ms
	// Example: 0
	ShieldCooldownMs int64 `json:"shieldCooldownMs,omitempty"`

	// shield left ms
	// Example: 0
	ShieldLeftMs int64 `json:"shieldLeftMs,omitempty"`

	// status
	// Example: alive
	// Enum: ["alive","dead"]
	Status string `json:"status,omitempty"`

	// velocity
	Velocity *PlaneVector `json:"velocity,omitempty"`

	// x
	// Example: 1
	// Required: true
	X *int64 `json:"x"`

	// y
	// Example: 1
	// Required: true
	Y *int64 `json:"y"`
}

// Validate validates this view transport
func (m *ViewTransport) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAnomalyAcceleration(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSelfAcceleration(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVelocity(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateX(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateY(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ViewTransport) validateAnomalyAcceleration(formats strfmt.Registry) error {
	if swag.IsZero(m.AnomalyAcceleration) { // not required
		return nil
	}

	if m.AnomalyAcceleration != nil {
		if err := m.AnomalyAcceleration.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("anomalyAcceleration")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("anomalyAcceleration")
			}
			return err
		}
	}

	return nil
}

func (m *ViewTransport) validateSelfAcceleration(formats strfmt.Registry) error {
	if swag.IsZero(m.SelfAcceleration) { // not required
		return nil
	}

	if m.SelfAcceleration != nil {
		if err := m.SelfAcceleration.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("selfAcceleration")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("selfAcceleration")
			}
			return err
		}
	}

	return nil
}

var viewTransportTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["alive","dead"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		viewTransportTypeStatusPropEnum = append(viewTransportTypeStatusPropEnum, v)
	}
}

const (

	// ViewTransportStatusAlive captures enum value "alive"
	ViewTransportStatusAlive string = "alive"

	// ViewTransportStatusDead captures enum value "dead"
	ViewTransportStatusDead string = "dead"
)

// prop value enum
func (m *ViewTransport) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, viewTransportTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *ViewTransport) validateStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.Status) { // not required
		return nil
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

func (m *ViewTransport) validateVelocity(formats strfmt.Registry) error {
	if swag.IsZero(m.Velocity) { // not required
		return nil
	}

	if m.Velocity != nil {
		if err := m.Velocity.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("velocity")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("velocity")
			}
			return err
		}
	}

	return nil
}

func (m *ViewTransport) validateX(formats strfmt.Registry) error {

	if err := validate.Required("x", "body", m.X); err != nil {
		return err
	}

	return nil
}

func (m *ViewTransport) validateY(formats strfmt.Registry) error {

	if err := validate.Required("y", "body", m.Y); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this view transport based on the context it is used
func (m *ViewTransport) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAnomalyAcceleration(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSelfAcceleration(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateVelocity(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ViewTransport) contextValidateAnomalyAcceleration(ctx context.Context, formats strfmt.Registry) error {

	if m.AnomalyAcceleration != nil {

		if swag.IsZero(m.AnomalyAcceleration) { // not required
			return nil
		}

		if err := m.AnomalyAcceleration.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("anomalyAcceleration")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("anomalyAcceleration")
			}
			return err
		}
	}

	return nil
}

func (m *ViewTransport) contextValidateSelfAcceleration(ctx context.Context, formats strfmt.Registry) error {

	if m.SelfAcceleration != nil {

		if swag.IsZero(m.SelfAcceleration) { // not required
			return nil
		}

		if err := m.SelfAcceleration.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("selfAcceleration")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("selfAcceleration")
			}
			return err
		}
	}

	return nil
}

func (m *ViewTransport) contextValidateVelocity(ctx context.Context, formats strfmt.Registry) error {

	if m.Velocity != nil {

		if swag.IsZero(m.Velocity) { // not required
			return nil
		}

		if err := m.Velocity.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("velocity")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("velocity")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ViewTransport) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ViewTransport) UnmarshalBinary(b []byte) error {
	var res ViewTransport
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
