// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ViewAnomaly view anomaly
//
// swagger:model view.Anomaly
type ViewAnomaly struct {

	// effective radius
	EffectiveRadius float64 `json:"effectiveRadius,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// radius
	Radius float64 `json:"radius,omitempty"`

	// strength
	Strength float64 `json:"strength,omitempty"`

	// velocity
	Velocity *PlaneVector `json:"velocity,omitempty"`

	// x
	// Example: 1
	// Required: true
	X *int64 `json:"x"`

	// y
	// Example: 1
	// Required: true
	Y *int64 `json:"y"`
}

// Validate validates this view anomaly
func (m *ViewAnomaly) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateVelocity(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateX(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateY(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ViewAnomaly) validateVelocity(formats strfmt.Registry) error {
	if swag.IsZero(m.Velocity) { // not required
		return nil
	}

	if m.Velocity != nil {
		if err := m.Velocity.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("velocity")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("velocity")
			}
			return err
		}
	}

	return nil
}

func (m *ViewAnomaly) validateX(formats strfmt.Registry) error {

	if err := validate.Required("x", "body", m.X); err != nil {
		return err
	}

	return nil
}

func (m *ViewAnomaly) validateY(formats strfmt.Registry) error {

	if err := validate.Required("y", "body", m.Y); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this view anomaly based on the context it is used
func (m *ViewAnomaly) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateVelocity(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ViewAnomaly) contextValidateVelocity(ctx context.Context, formats strfmt.Registry) error {

	if m.Velocity != nil {

		if swag.IsZero(m.Velocity) { // not required
			return nil
		}

		if err := m.Velocity.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("velocity")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("velocity")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ViewAnomaly) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ViewAnomaly) UnmarshalBinary(b []byte) error {
	var res ViewAnomaly
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
